name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: Set Git Configuration
        run: git config --global user.email "bot@example.com" &&  git config --global user.name "Package Update Bot"'

      - name: npm run bump
        run: npm run bump

      - name: npm run publish
        run: npm run publish
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
