name: PR

on:
  pull_request:
    branches: [master]

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run beachball:check
        run: npm run beachball:check

      - name: npm run build
        run: npm run build
