# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm ci
        run: npm ci
        
      - name: npm run beachball:check
        run: npm run beachball:check
        
      - name: npm run build
        run: npm run build
